#!/usr/bin/env node
// Pre-bundle codegen: inline customer-store/ assets into the tenant worker
// so the storefront is served from <subdomain>.upcart.online with no
// separate deploy step. Output: src/generated/storefront.ts (gitignored).

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const STORE_DIR = resolve(__dirname, "../customer-store");
const OUT_DIR   = resolve(__dirname, "src/generated");
const OUT_FILE  = join(OUT_DIR, "storefront.ts");

const HTML = "text/html; charset=utf-8";
const JS   = "application/javascript; charset=utf-8";
const CSS  = "text/css; charset=utf-8";

// Files to inline. `config.js` is intentionally regenerated to "" so the
// bundled storefront uses same-origin fetches.
const FILES = [
  { src: "index.html",    routes: ["/", "/index.html"], type: HTML },
  { src: "products.html", routes: ["/products.html"],   type: HTML },
  { src: "product.html",  routes: ["/product.html"],    type: HTML },
  { src: "cart.html",     routes: ["/cart.html"],       type: HTML },
  { src: "success.html",  routes: ["/success.html"],    type: HTML },
  { src: "cart.js",            routes: ["/cart.js"],            type: JS   },
  { src: "theme.js",           routes: ["/theme.js"],           type: JS   },
  { src: "sections.js",        routes: ["/sections.js"],        type: JS   },
  { src: "store-renderer.js",  routes: ["/store-renderer.js"],  type: JS   },
];

function read(rel) {
  const p = join(STORE_DIR, rel);
  if (!existsSync(p)) throw new Error(`Missing asset: ${p}`);
  return readFileSync(p, "utf8");
}

const assets = [];

for (const { src, routes, type } of FILES) {
  const body = read(src);
  for (const route of routes) {
    assets.push({ route, body, type });
  }
}

// Override config.js — empty base = same origin
assets.push({
  route: "/config.js",
  body:  'window.BST_API_BASE="";\n',
  type:  JS,
});

// Theme CSS files
const themesDir = join(STORE_DIR, "themes");
if (existsSync(themesDir)) {
  for (const name of readdirSync(themesDir)) {
    if (!name.endsWith(".css")) continue;
    assets.push({
      route: `/themes/${name}`,
      body:  readFileSync(join(themesDir, name), "utf8"),
      type:  CSS,
    });
  }
}

mkdirSync(OUT_DIR, { recursive: true });

const entries = assets
  .map(
    (a) =>
      `  ${JSON.stringify(a.route)}: { body: ${JSON.stringify(a.body)}, type: ${JSON.stringify(a.type)} },`
  )
  .join("\n");

const out = `// AUTO-GENERATED by backend/build.mjs — do not edit.
// Source: ../customer-store/. Regenerate with \`npm run build\`.

export const STOREFRONT_ASSETS: Record<string, { body: string; type: string }> = {
${entries}
};
`;

writeFileSync(OUT_FILE, out);

const total = assets.reduce((s, a) => s + a.body.length, 0);
console.log(
  `storefront codegen → ${OUT_FILE} (${assets.length} routes, ${(total / 1024).toFixed(1)} KB)`
);
